# services:
#   - type: web
#     name: api-gateway
#     env: docker
#     repo: https://github.com/XKolz/pitch-deck-parser
#     region: oregon
#     branch: main
#     dockerfilePath: api_gateway/Dockerfile
#     buildCommand: ""
#     startCommand: "python app.py"
#     envVars:
#       - key: DB_URL
#         fromDatabase:
#           name: pitchdeck-db
#           property: connectionString
#       - key: REDIS_URL
#         fromService:
#           name: pitchdeck-redis
#           type: redis

#   - type: worker
#     name: parser-service
#     env: docker
#     repo: https://github.com/XKolz/pitch-deck-parser
#     region: oregon
#     branch: main
#     dockerfilePath: parser_service/Dockerfile
#     buildCommand: ""
#     startCommand: "celery -A tasks worker --loglevel=info"
#     envVars:
#       - key: DB_URL
#         fromDatabase:
#           name: pitchdeck-db
#           property: connectionString
#       - key: REDIS_URL
#         fromService:
#           name: pitchdeck-redis
#           type: redis

# databases:
#   - name: pitchdeck-db
#     region: oregon
#     plan: free

# redis:
#   - name: pitchdeck-redis
#     region: oregon
#     plan: free
services:
  - type: web
    name: api-gateway
    env: docker
    repo: https://github.com/XKolz/pitch-deck-parser
    dockerfilePath: api_gateway/Dockerfile
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: DB_URL
        fromService:
          name: pitchdeck-db
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pitchdeck-redis
          type: redis
          property: connectionString

  - type: worker
    name: parser-service
    env: docker
    repo: https://github.com/XKolz/pitch-deck-parser
    dockerfilePath: parser_service/Dockerfile
    startCommand: celery -A tasks worker --loglevel=info
    plan: free
    envVars:
      - key: DB_URL
        fromService:
          name: pitchdeck-db
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pitchdeck-redis
          type: redis
          property: connectionString

databases:
  - name: pitchdeck-db
    plan: free
    databaseName: pitchdeck
    user: user

  - name: pitchdeck-redis
    plan: free
