services:
  - name: api-gateway
    type: web
    env: docker
    plan: free
    repo: https://github.com/XKolz/pitch-deck-parser
    region: oregon
    dockerfilePath: api_gateway/Dockerfile
    buildFilter:
      paths:
        - api_gateway/**
    envVars:
      - key: DB_URL
        value: postgres://user:password@pitchdeck-db:5432/pitchdeck
      - key: CELERY_BROKER_URL
        value: redis://pitchdeck-redis:6379/0

  - name: parser-service
    type: worker
    env: docker
    plan: free
    repo: https://github.com/XKolz/pitch-deck-parser
    region: oregon
    dockerfilePath: parser_service/Dockerfile
    buildFilter:
      paths:
        - parser_service/**
    envVars:
      - key: DB_URL
        value: postgres://user:password@pitchdeck-db:5432/pitchdeck
      - key: CELERY_BROKER_URL
        value: redis://pitchdeck-redis:6379/0

databases:
  - name: pitchdeck-db
    databaseName: pitchdeck
    user: user
